export const MANUFACTURERS = [
    "Abarth",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Dodge",
    "Donkervoort",
    "DS",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kia",
    "KTM",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Lexus",
    "Lotus",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "Opel",
    "Peugeot",
    "Porsche",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "Seat",
    "Skoda",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
];

export const BANKS = [
    "9mobile 9Payment Service Bank",
    "Abbey Mortgage Bank",
    "Above Only MFB",
    "Abulesoro MFB",
    "Access Bank",
    "Access Bank (Diamond)",
    "Airtel Smartcash PSB",
    "ALAT by WEMA",
    "Amju Unique MFB",
    "Aramoko MFB",
    "ASO Savings and Loans",
    "Astrapolaris MFB LTD",
    "Bainescredit MFB",
    "Bowen Microfinance Bank",
    "Carbon",
    "CEMCS Microfinance Bank",
    "Chanelle Microfinance Bank Limited",
    "Citibank Nigeria",
    "Corestep MFB",
    "Coronation Merchant Bank",
    "Crescent MFB",
    "Ecobank Nigeria",
    "Ekimogun MFB",
    "Ekondo Microfinance Bank",
    "Eyowo",
    "Fidelity Bank",
    "Firmus MFB",
    "First Bank of Nigeria",
    "First City Monument Bank",
    "FSDH Merchant Bank Limited",
    "Gateway Mortgage Bank LTD",
    "Globus Bank",
    "GoMoney",
    "Guaranty Trust Bank",
    "Hackman Microfinance Bank",
    "Hasal Microfinance Bank",
    "Heritage Bank",
    "HopePSB",
    "Ibile Microfinance Bank",
    "Ikoyi Osun MFB",
    "Infinity MFB",
    "Jaiz Bank",
    "Kadpoly MFB",
    "Keystone Bank",
    "Kredi Money MFB LTD",
    "Kuda Bank",
    "Lagos Building Investment Company Plc.",
    "Links MFB",
    "Living Trust Mortgage Bank",
    "Lotus Bank",
    "Mayfair MFB",
    "Mint MFB",
    "MTN Momo PSB",
    "Paga",
    "PalmPay",
    "Parallex Bank",
    "Parkway - ReadyCash",
    "Paycom",
    "Petra Mircofinance Bank Plc",
    "Polaris Bank",
    "Polyunwana MFB",
    "PremiumTrust Bank",
    "Providus Bank",
    "QuickFund MFB",
    "Rand Merchant Bank",
    "Refuge Mortgage Bank",
    "Rubies MFB",
    "Safe Haven MFB",
    "Solid Rock MFB",
    "Sparkle Microfinance Bank",
    "Stanbic IBTC Bank",
    "Standard Chartered Bank",
    "Stellas MFB",
    "Sterling Bank",
    "Suntrust Bank",
    "TAJ Bank",
    "Tangerine Money",
    "TCF MFB",
    "Titan Bank",
    "Titan Paystack",
    "Unical MFB",
    "Union Bank of Nigeria",
    "United Bank For Africa",
    "Unity Bank",
    "VFD Microfinance Bank Limited",
    "Wema Bank",
    "Zenith Bank",    
];

export const BILLING_TYPES = [
    {
        label: 'Individual',
        value: 'individual',
    },
    {
        label: 'Corporate',
        value: 'corporate'
    }
];

export const BUS_TYPES = [
    {
        label: 'Coach',
        value: 'Coach'
    },
    {
        label: 'Shuttle',
        value: 'Shuttle'
    },
    {
        label: 'Minibus',
        value: 'Minibus'
    },
    {
        label: 'Double Decker',
        value: 'Double Decker'
    },
];